version: '2'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /flow-library/node_modules # prevent them being overwritten by the above
      - .:/flow-library
    ports:
      - "7000:7000"
      - "5858:5858"
    links:
      - mongo
    environment:
      NODE_ENV: development
      FLOW_SETTINGS: ../settings-dev.js
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
